#define BLUETOOTH_ADDRESS 12

#define STORAGE_TUBE_AVAILABILITY 0x01
#define SUPPLY_TUBE_AVAILABILITY 0x02
#define RADIATION_ALERT 0x03
#define STOP_MOVEMENT 0x04
#define RESUME_MOVEMENT 0x05
#define ROBOT_STATUS 0x06
#define HEART_BEAT 0x07

#define CARRYING_SPENT_FUEL_ROD 0x2C
#define CARRYING_NEW_FUEL_ROD 0xFF
